version: '3.8'

services:
  ha-fusion-custom:
    build:
      context: .
      dockerfile: Dockerfile.custom
    container_name: ha-fusion-custom
    ports:
      - "5050:5050"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - homeassistant

networks:
  homeassistant:
    external: true