overrides:
  '@eslint/plugin-kit@<0.2.3': '>=0.2.3'
  '@eslint/plugin-kit@<0.3.4': '>=0.3.4'
  '@sveltejs/kit@<2.8.3': '>=2.8.3'
  '@sveltejs/kit@>=2.0.0 <2.20.6': '>=2.20.6'
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12'
  brace-expansion@>=2.0.0 <=2.0.1: '>=2.0.2'
  cookie@<0.7.0: '>=0.7.0'
  cross-spawn@>=7.0.0 <7.0.5: '>=7.0.5'
  devalue@<5.3.2: '>=5.3.2'
  esbuild@<=0.24.2: '>=0.25.0'
  nanoid@<3.3.8: '>=3.3.8'
  path-to-regexp@<0.1.12: '>=0.1.12'
  undici@<5.29.0: '>=5.29.0'
  undici@>=4.5.0 <5.28.5: '>=5.28.5'
