name: 'HA Fusion Custom'
description: 'Home Assistant dashboard personalizzato con componente Bar universale'
version: '2024.10.0-custom'
slug: 'ha-fusion-custom'
init: false
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
ports:
  5050/tcp: 5050
ports_description:
  5050/tcp: 'Interfaccia Web HA Fusion Custom'
webui: 'http://[HOST]:[PORT:5050]'
panel_icon: 'mdi:view-dashboard-variant'
panel_title: 'HA Fusion Custom'
ingress: true
ingress_port: 5050
ingress_entry: '/'
startup: services
options:
  log_level: info
schema:
  log_level: 'list(trace|debug|info|notice|warning|error|fatal)?'
image: 'ghcr.io/home-assistant/{arch}-addon-ha-fusion-custom'
